use crate::models::{Conference, Division};

#[derive(Clone, Debug)]
pub struct TeamSeed {
    pub city: &'static str,
    pub name: &'static str,
    pub conference: Conference,
    pub division: Division,
}

pub const ROSTER_SIZE: usize = 12;
pub const DEFAULT_SEASON: u16 = 2027;

pub const NBA_NICKNAMES: &[&str] = &[
    "76ers",
    "Bucks",
    "Bulls",
    "Cavaliers",
    "Celtics",
    "Clippers",
    "Grizzlies",
    "Hawks",
    "Heat",
    "Hornets",
    "Jazz",
    "Kings",
    "Knicks",
    "Lakers",
    "Magic",
    "Mavericks",
    "Nets",
    "Nuggets",
    "Pacers",
    "Pelicans",
    "Pistons",
    "Raptors",
    "Rockets",
    "Spurs",
    "Suns",
    "Thunder",
    "Timberwolves",
    "Trail Blazers",
    "Warriors",
    "Wizards",
];

pub const TEAM_SEEDS: &[TeamSeed] = &[
    TeamSeed {
        city: "Boston",
        name: "Harbors",
        conference: Conference::East,
        division: Division::Atlantic,
    },
    TeamSeed {
        city: "Brooklyn",
        name: "Bridges",
        conference: Conference::East,
        division: Division::Atlantic,
    },
    TeamSeed {
        city: "New York",
        name: "Skylines",
        conference: Conference::East,
        division: Division::Atlantic,
    },
    TeamSeed {
        city: "Philadelphia",
        name: "Founders",
        conference: Conference::East,
        division: Division::Atlantic,
    },
    TeamSeed {
        city: "Toronto",
        name: "Towers",
        conference: Conference::East,
        division: Division::Atlantic,
    },
    TeamSeed {
        city: "Chicago",
        name: "Junctions",
        conference: Conference::East,
        division: Division::Central,
    },
    TeamSeed {
        city: "Cleveland",
        name: "Forges",
        conference: Conference::East,
        division: Division::Central,
    },
    TeamSeed {
        city: "Detroit",
        name: "Motors",
        conference: Conference::East,
        division: Division::Central,
    },
    TeamSeed {
        city: "Indiana",
        name: "Harvest",
        conference: Conference::East,
        division: Division::Central,
    },
    TeamSeed {
        city: "Milwaukee",
        name: "Foundry",
        conference: Conference::East,
        division: Division::Central,
    },
    TeamSeed {
        city: "Atlanta",
        name: "Flight",
        conference: Conference::East,
        division: Division::Southeast,
    },
    TeamSeed {
        city: "Charlotte",
        name: "Crowns",
        conference: Conference::East,
        division: Division::Southeast,
    },
    TeamSeed {
        city: "Miami",
        name: "Breakers",
        conference: Conference::East,
        division: Division::Southeast,
    },
    TeamSeed {
        city: "Orlando",
        name: "Sparks",
        conference: Conference::East,
        division: Division::Southeast,
    },
    TeamSeed {
        city: "Washington",
        name: "Capitals",
        conference: Conference::East,
        division: Division::Southeast,
    },
    TeamSeed {
        city: "Pittsburgh",
        name: "Iron",
        conference: Conference::East,
        division: Division::Central,
    },
    TeamSeed {
        city: "Denver",
        name: "Summits",
        conference: Conference::West,
        division: Division::Northwest,
    },
    TeamSeed {
        city: "Minnesota",
        name: "Northstars",
        conference: Conference::West,
        division: Division::Northwest,
    },
    TeamSeed {
        city: "Oklahoma City",
        name: "Barons",
        conference: Conference::West,
        division: Division::Northwest,
    },
    TeamSeed {
        city: "Portland",
        name: "Bridges",
        conference: Conference::West,
        division: Division::Northwest,
    },
    TeamSeed {
        city: "Utah",
        name: "Canyons",
        conference: Conference::West,
        division: Division::Northwest,
    },
    TeamSeed {
        city: "Golden State",
        name: "Gatekeepers",
        conference: Conference::West,
        division: Division::Pacific,
    },
    TeamSeed {
        city: "LA",
        name: "Stars",
        conference: Conference::West,
        division: Division::Pacific,
    },
    TeamSeed {
        city: "Los Angeles",
        name: "Voyagers",
        conference: Conference::West,
        division: Division::Pacific,
    },
    TeamSeed {
        city: "Phoenix",
        name: "Embers",
        conference: Conference::West,
        division: Division::Pacific,
    },
    TeamSeed {
        city: "Sacramento",
        name: "Railers",
        conference: Conference::West,
        division: Division::Pacific,
    },
    TeamSeed {
        city: "Dallas",
        name: "Rangers",
        conference: Conference::West,
        division: Division::Southwest,
    },
    TeamSeed {
        city: "Houston",
        name: "Comets",
        conference: Conference::West,
        division: Division::Southwest,
    },
    TeamSeed {
        city: "Memphis",
        name: "Rivercats",
        conference: Conference::West,
        division: Division::Southwest,
    },
    TeamSeed {
        city: "New Orleans",
        name: "Crescents",
        conference: Conference::West,
        division: Division::Southwest,
    },
    TeamSeed {
        city: "San Antonio",
        name: "Missions",
        conference: Conference::West,
        division: Division::Southwest,
    },
    TeamSeed {
        city: "Seattle",
        name: "Sound",
        conference: Conference::West,
        division: Division::Northwest,
    },
];

pub const FIRST_NAMES: &[&str] = &[
    "Andre", "Bennett", "Caleb", "Darius", "Elliot", "Felix", "Gabe", "Holden", "Isaiah", "Jalen",
    "Kai", "Landon", "Malik", "Nico", "Owen", "Porter", "Quincy", "Rafael", "Silas", "Theo", "Uri",
    "Vince", "Wes", "Xavier", "Yusuf", "Zane",
];

pub const LAST_NAMES: &[&str] = &[
    "Archer",
    "Bishop",
    "Carter",
    "Dawson",
    "Ellis",
    "Foster",
    "Grant",
    "Hayes",
    "Irving",
    "Jennings",
    "Keller",
    "Lawson",
    "Mercer",
    "Nash",
    "Owens",
    "Pierce",
    "Quinn",
    "Reeves",
    "Sutton",
    "Turner",
    "Underwood",
    "Vaughn",
    "Walker",
    "Young",
    "Zimmer",
];
